baseURL = "https://zburu.com"
languageCode = "en-us"
title = "子舒的博客"
theme = "Reader"
paginate = 7

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  title = "子舒的博客"
  favicon = "https://cdn.zburu.com/favicon.ico"
  buildDate = "2020-06-14"
  beian = "浙ICP备2022002453号-2"

[permalinks]
  posts = "/archives/:slug.html"

[[params.socials]]
name = "归档"
link = "/posts"

[[params.socials]]
name = "周刊"
link = "/weekly"

[[params.socials]]
name = "留言"
link = "/message"

[[params.socials]]
name = "关于"
link = "/about"

[[params.socials]]
name = "说说"
link = "/shuoshuo"

[[params.socials]]
name = "实验室"
link = "/lab"